Critter/src/main/java/com/techelevator/critter/model/Conversation.java
package com.techelevator.critter.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Conversation {
	
	private String forUser;
	private String withUser;
	private List<Message> messages;
	
	public Conversation() {
		messages = new ArrayList<>();
	}
	
	public String getForUser() {
		return forUser;
	}
	public void setForUser(String forUser) {
		this.forUser = forUser;
	}
	public String getWithUser() {
		return withUser;
	}
	public void setWithUser(String withUser) {
		this.withUser = withUser;
	}
	public List<Message> getMessages() {
		return Collections.unmodifiableList(messages);
	}
	public Message getLatestMessage() {
		return messages.get(0);
	}
	public void addMessage(Message message) {
		messages.add(message);
	}
}

Critter/src/main/java/com/techelevator/critter/model/Message.java
package com.techelevator.critter.model;

import java.time.LocalDateTime;

public class Message {

	private Long id;
	private String fromUsername;
	private String toUsername;
	private String text;
	private boolean isPrivate = false;
	private LocalDateTime createTime;	

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getFromUsername() {
		return fromUsername;
	}
	public void setFromUsername(String fromUsername) {
		this.fromUsername = fromUsername;
	}
	public String getToUsername() {
		return toUsername;
	}
	public void setToUsername(String toUsername) {
		this.toUsername = toUsername;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public boolean isPrivate() {
		return isPrivate;
	}
	public void setPrivate(boolean isPrivate) {
		this.isPrivate = isPrivate;
	}
	public LocalDateTime getCreateTime() {
		return createTime;
	}
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime = createTime;
	}
}

Critter/src/main/java/com/techelevator/critter/controller/HomeController.java
package com.techelevator.critter.controller;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.techelevator.critter.model.MessageDAO;

@Controller
public class HomeController {
	
	private MessageDAO messageDAO;

	@Autowired
	public HomeController(MessageDAO messageDAO) {
		this.messageDAO = messageDAO;
	}
	
	@RequestMapping(path="/", method=RequestMethod.GET)
	public String showHomePage(Map<String, Object> model) {
		model.put("messages", messageDAO.getPublicMessages(10));
		return "home";
	}
}

Critter/src/main/java/com/techelevator/critter/controller/MessageController.java
package com.techelevator.critter.controller;

import java.time.LocalDateTime;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.techelevator.critter.model.Message;
import com.techelevator.critter.model.MessageDAO;

@Controller
public class MessageController {
	
	private MessageDAO messageDAO;

	@Autowired
	public MessageController(MessageDAO messageDAO) {
		this.messageDAO = messageDAO;
	}

	@RequestMapping(path="/messages", method=RequestMethod.GET)
	public String messageSearch(Map<String, Object> model, 
								@RequestParam String userName) {
		
		model.put("messages", messageDAO.searchByUsername(userName));
		return "messages";
	}
	
	@RequestMapping(path="/users/{userName}/messages/new", method=RequestMethod.GET)
	public String displayMessageForm() {
		return "newMessage";
	}
	
	@RequestMapping(path="/users/{userName}/messages", method=RequestMethod.POST)
	public String createNewMessage(@PathVariable String userName,
								   @RequestParam String visibility, 
								   @RequestParam(required=false) String messageTo, 
								   @RequestParam String messageText) {
		
		Message message = new Message();
		message.setFromUsername(userName);
		message.setText(messageText);
		message.setCreateTime(LocalDateTime.now());
		if("private".equals(visibility)) {
			message.setPrivate(true);
			message.setToUsername(messageTo);
		}
		messageDAO.saveMessage(message);
		
		return "redirect:/users/"+userName+"/messages";
	}
}

Critter/src/main/webapp/WEB-INF/jsp/changePassword.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<script type="text/javascript">
	$(document).ready(function () {
	
		$("#changePasswordForm").validate({
			
			rules : {
				
				password : {
					required : true
				},
				confirmPassword : {
					required : true,		
					equalTo : "#password"  
				}
			},
			messages : {			
				confirmPassword : {
					equalTo : "Passwords do not match"
				}
			},
			errorClass : "error"
		});
	});
</script>


<h2>Change Password</h2>

<c:url var="formAction" value="/users/${userName}/changePassword" />

<div class="row">
	<div class="col-md-5">
		<form action="${formAction}" method="POST" id="changePasswordForm">
			<div class="form-group">
				<label for="password">New Password: </label>
				<input type="password" id="password" name="password" class="form-control" />	
			</div>
			<div class="form-group">
				<label for="confirmPassword">Confirm Password: </label>
				<input type="password" id="confirmPassword" name="confirmPassword" class="form-control" />	
			</div>
			<button type="submit" class="btn btn-default">Change Password</button>
		</form>
	</div>

	<div class="col-md-9"></div>
</div>

<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/conversation.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<h2>Private Conversation with ${conversation.withUser}</h2>

<ol class="message-list">
	<c:forEach items="${conversation.messages}" var="message">
		<c:choose>
			<c:when test="${conversation.forUser == message.fromUsername}">
				<c:set var="fromto" value="from" />
			</c:when>
			<c:otherwise>
				<c:set var="fromto" value="to" />
			</c:otherwise>
		</c:choose>
		<li class="message ${fromto}">
			<span class="username">${message.fromUsername}</span>
			<span class="message-text">${message.text}</span>
			<time class="timeago" datetime="${message.createTime}">${message.createTime}</time>
		</li>
	</c:forEach>
</ol>

<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/footer.jsp
		</div>
		
		<footer>
			Copyright 2016 Critter Inc.
		</footer>
	</body>
</html>

Critter/src/main/webapp/WEB-INF/jsp/header.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<!DOCTYPE html>
<html>
	<head>
		<title>Critter</title>
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	    <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
	    <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.js "></script>
	    <script src="https://cdn.jsdelivr.net/jquery.timeago/1.4.1/jquery.timeago.min.js"></script>
	    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	    <c:url var="cssHref" value="/site.css" />
		<link rel="stylesheet" type="text/css" href="${cssHref}">
		
		<script type="text/javascript">
			$(document).ready(function() {
				$("time.timeago").timeago();
				
				$("#logoutLink").click(function(event){
					$("#logoutForm").submit();
				});
				
				var pathname = window.location.pathname;
				$("nav a[href='"+pathname+"']").parent().addClass("active");
				
			});
			
			
		</script>
		
	</head>
	<body>
		<header>
			<c:url var="homePageHref" value="/" />
			<c:url var="imgSrc" value="/img/logo.png" />
			<a href="${homePageHref}"><img src="${imgSrc}" class="img-responsive" /></a>
		</header>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<c:url var="homePageHref" value="/" />
					<li><a href="${homePageHref}">Home</a></li>
					<c:if test="${not empty currentUser}">
						<c:url var="dashboardHref" value="/users/${currentUser}" />
						<li><a href="${dashboardHref}">Private Messages</a></li>
						<c:url var="newMessageHref" value="/users/${currentUser}/messages/new" />
						<li><a href="${newMessageHref}">New Message</a></li>
						<c:url var="sentMessagesHref" value="/users/${currentUser}/messages" />
						<li><a href="${sentMessagesHref}">Sent Messages</a></li>
						<c:url var="changePasswordHref" value="/users/${currentUser}/changePassword" />
						<li><a href="${changePasswordHref}">Change Password</a></li>
					</c:if>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<c:choose>
						<c:when test="${empty currentUser}">
							<c:url var="newUserHref" value="/users/new" />
							<li><a href="${newUserHref}">Sign Up</a></li>
							<c:url var="loginHref" value="/login" />
							<li><a href="${loginHref}">Log In</a></li>
						</c:when>
						<c:otherwise>
							<c:url var="logoutAction" value="/logout" />
							<form id="logoutForm" action="${logoutAction}" method="POST"></form>
							<li><a id="logoutLink" href="#">Log Out</a></li>
						</c:otherwise>
					</c:choose>
				</ul>
			</div>
		</nav>
		<c:if test="${not empty currentUser}">
			<p id="currentUser">Current User: ${currentUser}</p>
		</c:if>		
		<div class="container">

Critter/src/main/webapp/WEB-INF/jsp/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<h2>Latest Messages</h2>
<ol class="message-list">
	<c:forEach items="${messages}" var="message">
		<li class="message">
			<c:url var="messageHref" value="/messages">
				<c:param name="userName" value="${message.fromUsername}" />
			</c:url>
			<span class="username"><a href="${messageHref}">${message.fromUsername}</a></span>
			<span class="message-text">${message.text}</span>
			<time class="timeago" datetime="${message.createTime}">${message.createTime}</time>
		</li>
	</c:forEach>
</ol>
		
<c:import url="/WEB-INF/jsp/footer.jsp" />
		

Critter/src/main/webapp/WEB-INF/jsp/login.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<script type="text/javascript">
	$(document).ready(function () {
	
		$("form").validate({
			
			rules : {
				userName : {
					required : true
				},
				password : {
					required : true
				}
			},
			messages : {			
				confirmPassword : {
					equalTo : "Passwords do not match"
				}
			},
			errorClass : "error"
		});
	});
</script>

<div class="row">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">
		<c:url var="formAction" value="/login" />
		<form method="POST" action="${formAction}">
			<div class="form-group">
				<label for="userName">User Name: </label>
				<input type="text" id="userName" name="userName" placeHolder="User Name" class="form-control" />
			</div>
			<div class="form-group">
				<label for="password">Password: </label>
				<input type="password" id="password" name="password" placeHolder="Password" class="form-control" />
			</div>
			<button type="submit" class="btn btn-default">Login</button>
		</form>
	</div>
	<div class="col-sm-4"></div>
</div>
<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/messages.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<h2>Latest Messages From ${param.userName}</h2>

<ol class="message-list">
	<c:forEach items="${messages}" var="message">
		<li class="message">
			<span class="message-text">${message.text}</span>
			<time class="timeago" datetime="${message.createTime}">${message.createTime}</time>
		</li>
	</c:forEach>
</ol>

<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/newMessage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<script type="text/javascript">
	var $messageTo;
	
	$(document).ready(function () {
		
		$messageTo = $("#messageTo").parent().detach();
		
		$("#visibility").change(function(event) {
			if($(this).val() == "private") {
				$(this).parent().after($messageTo);
			} else {
				$messageTo = $("#messageTo").parent().detach();
			}
		});	
	});
</script>

<h2>New Message</h2>

<c:url var="formAction" value="/users/${currentUser}/messages" />

<div class="row">
	<div class="col-md-5">
		<form action="${formAction}" method="POST">
			<div class="form-group">
				<select id="visibility" name="visibility" class="form-control">
					<option value="public">Public</option>
					<option value="private">Private</option>
				</select>
			</div>
			<div class="form-group">
				<label for="messageTo">To: </label>
				<input type="text" id="messageTo" name="messageTo" class="form-control" />	
			</div>
			<div class="form-group">
				<textarea id="messageText" name="messageText" class="form-control" rows="3" cols="50" placeholder="Your message goes here (140 character max)" maxlength="140"></textarea>	
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>

	<div class="col-md-9"></div>
</div>

<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/newUser.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<script type="text/javascript">
	$(document).ready(function () {
	
		$("form").validate({
			
			rules : {
				userName : {
					required : true
				},
				password : {
					required : true
				},
				confirmPassword : {
					required : true,		
					equalTo : "#password"  
				}
			},
			messages : {			
				confirmPassword : {
					equalTo : "Passwords do not match"
				}
			},
			errorClass : "error"
		});
	});
</script>

<c:url var="formAction" value="/users" />
<form method="POST" action="${formAction}">
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
			<div class="form-group">
				<label for="userName">User Name: </label>
				<input type="text" id="userName" name="userName" placeHolder="User Name" class="form-control" />
			</div>
			<div class="form-group">
				<label for="password">Password: </label>
				<input type="password" id="password" name="password" placeHolder="Password" class="form-control" />
			</div>
			<div class="form-group">
				<label for="confirmPassword">Confirm Password: </label>
				<input type="password" id="confirmPassword" name="confirmPassword" placeHolder="Re-Type Password" class="form-control" />	
			</div>
			<button type="submit" class="btn btn-default">Create User</button>
		</div>
		<div class="col-sm-4"></div>
	</div>
</form>
		
<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/sentMessages.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<h2>Sent Messages</h2>

<ol class="message-list">
	<c:forEach items="${messages}" var="message">
		<li class="message">
			<c:if test="${not empty message.toUsername}">
				<c:url var="conversationHref" value="/users/${message.fromUsername}/conversations/${message.toUsername}" />
				<span class="username">
					<a href="${conversationHref}">@${message.toUsername}</a>
				</span>
			</c:if>
			<span class="message-text">${message.text}</span>
			<time class="timeago" datetime="${message.createTime}">${message.createTime}</time>
		</li>
	</c:forEach>
</ol>

<c:import url="/WEB-INF/jsp/footer.jsp" />

Critter/src/main/webapp/WEB-INF/jsp/userDashboard.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

<h2>Latest Private Messages</h2>
<ol class="message-list">
	<c:forEach var="conversation" items="${conversations}">
		<li class="message">
			<c:url var="conversationHref" value="/users/${conversation.forUser}/conversations/${conversation.withUser}" />
			<span class="username"><a href="${conversationHref}">${conversation.withUser}</a></span>
			<span class="message-text">${conversation.latestMessage.text}</span>
			<time class="timeago" datetime="${conversation.latestMessage.createTime}">${conversation.latestMessage.createTime}</time>
		</li>
	</c:forEach>
</ol>

<c:import url="/WEB-INF/jsp/footer.jsp" />